version: '3.8'
services:
  review-service:
    build: .
    image: ya-workshop-review-service
    container_name: review-service
    ports:
      - "8085:8090"
    depends_on:
      - review-service-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://review-service-db:5432/review-service
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  review-service-db:
    image: postgres:14-alpine
    container_name: review-service-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=review-service
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root